const { COLORS, ROLE_IDS } = require("../config");
const { compact, request } = require("./factory");

const physRankIds = compact(Object.values(ROLE_IDS.ranks.phys));
const ptolRankIds = compact(Object.values(ROLE_IDS.ranks.ptol));

function rank({ key, label, code, group, branch, color, emoji, target, current, currentLabel, major, removeRoleIds }) {
  return request({
    key,
    label,
    code,
    group,
    category: "rank",
    branch,
    emoji,
    accentColor: color,
    targetRoleId: target,
    grantRoleIds: compact([target]),
    removeRoleIds,
    requireAllRoleIds: compact([major, current]),
    requiredCurrentRankRoleId: current,
    requiredCurrentRankLabel: currentLabel,
    requiredConfigIds: [major, current, target],
    formType: "rank",
  });
}

const RANK_REQUESTS = {
  rank_phys_sous_officier: rank({
    key: "rank_phys_sous_officier",
    label: "Sous-Officier - PHYS",
    code: "RANK // PHYS // SOUS-OFFICIER",
    group: "rank_phys",
    branch: "phys",
    color: COLORS.PHYS_BLUE,
    emoji: "🔵",
    target: ROLE_IDS.ranks.phys.sousOfficier,
    current: ROLE_IDS.ranks.phys.mdr,
    currentLabel: "Militaire du Rang - PHYS",
    major: ROLE_IDS.major.physique,
    removeRoleIds: physRankIds,
  }),
  rank_phys_officier: rank({
    key: "rank_phys_officier",
    label: "Officier - PHYS",
    code: "RANK // PHYS // OFFICIER",
    group: "rank_phys",
    branch: "phys",
    color: COLORS.PHYS_BLUE,
    emoji: "🔵",
    target: ROLE_IDS.ranks.phys.officier,
    current: ROLE_IDS.ranks.phys.sousOfficier,
    currentLabel: "Sous-Officier - PHYS",
    major: ROLE_IDS.major.physique,
    removeRoleIds: physRankIds,
  }),
  rank_phys_co_gerant: rank({
    key: "rank_phys_co_gerant",
    label: "Co-Gérant - PHYS",
    code: "RANK // PHYS // CO-GÉRANT",
    group: "rank_phys",
    branch: "phys",
    color: COLORS.PHYS_BLUE,
    emoji: "🔵",
    target: ROLE_IDS.ranks.phys.coGerant,
    current: ROLE_IDS.ranks.phys.officier,
    currentLabel: "Officier - PHYS",
    major: ROLE_IDS.major.physique,
    removeRoleIds: physRankIds,
  }),
  rank_phys_gerant: rank({
    key: "rank_phys_gerant",
    label: "Gérant - PHYS",
    code: "RANK // PHYS // GÉRANT",
    group: "rank_phys",
    branch: "phys",
    color: COLORS.PHYS_BLUE,
    emoji: "🔵",
    target: ROLE_IDS.ranks.phys.gerant,
    current: ROLE_IDS.ranks.phys.coGerant,
    currentLabel: "Co-Gérant - PHYS",
    major: ROLE_IDS.major.physique,
    removeRoleIds: physRankIds,
  }),

  rank_ptol_sous_officier: rank({
    key: "rank_ptol_sous_officier",
    label: "Sous-Officier - PTOL",
    code: "RANK // PTOL // SOUS-OFFICIER",
    group: "rank_ptol",
    branch: "ptol",
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟢",
    target: ROLE_IDS.ranks.ptol.sousOfficier,
    current: ROLE_IDS.ranks.ptol.mdr,
    currentLabel: "Militaire du Rang - PTOL",
    major: ROLE_IDS.major.ptolemee,
    removeRoleIds: ptolRankIds,
  }),
  rank_ptol_officier: rank({
    key: "rank_ptol_officier",
    label: "Officier - PTOL",
    code: "RANK // PTOL // OFFICIER",
    group: "rank_ptol",
    branch: "ptol",
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟢",
    target: ROLE_IDS.ranks.ptol.officier,
    current: ROLE_IDS.ranks.ptol.sousOfficier,
    currentLabel: "Sous-Officier - PTOL",
    major: ROLE_IDS.major.ptolemee,
    removeRoleIds: ptolRankIds,
  }),
  rank_ptol_co_gerant: rank({
    key: "rank_ptol_co_gerant",
    label: "Co-Gérant - PTOL",
    code: "RANK // PTOL // CO-GÉRANT",
    group: "rank_ptol",
    branch: "ptol",
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟢",
    target: ROLE_IDS.ranks.ptol.coGerant,
    current: ROLE_IDS.ranks.ptol.officier,
    currentLabel: "Officier - PTOL",
    major: ROLE_IDS.major.ptolemee,
    removeRoleIds: ptolRankIds,
  }),
  rank_ptol_gerant: rank({
    key: "rank_ptol_gerant",
    label: "Gérant - PTOL",
    code: "RANK // PTOL // GÉRANT",
    group: "rank_ptol",
    branch: "ptol",
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟢",
    target: ROLE_IDS.ranks.ptol.gerant,
    current: ROLE_IDS.ranks.ptol.coGerant,
    currentLabel: "Co-Gérant - PTOL",
    major: ROLE_IDS.major.ptolemee,
    removeRoleIds: ptolRankIds,
  }),
};

module.exports = { RANK_REQUESTS };
