const { COLORS, ROLE_IDS } = require("../config");
const { compact, request } = require("./factory");

function specialization({ key, label, code, group, branch, target, major, color, emoji }) {
  return request({
    key,
    label,
    code,
    group,
    category: "specialization",
    branch,
    emoji,
    accentColor: color,
    targetRoleId: target,
    grantRoleIds: compact([target]),
    requireAllRoleIds: compact([major]),
    requiredConfigIds: [major, target],
    formType: "specialization",
  });
}

const SPECIALIZATION_REQUESTS = {
  spec_phys_cqb: specialization({
    key: "spec_phys_cqb",
    label: "Unité CQB/CQC",
    code: "SPEC // PHYS // CQB-CQC",
    group: "spec_phys",
    branch: "phys",
    target: ROLE_IDS.specializations.phys.cqb,
    major: ROLE_IDS.major.physique,
    color: COLORS.PHYS_BLUE,
    emoji: "🔷",
  }),
  spec_phys_appui_feu: specialization({
    key: "spec_phys_appui_feu",
    label: "Unité d'Appui Feu",
    code: "SPEC // PHYS // APPUI-FEU",
    group: "spec_phys",
    branch: "phys",
    target: ROLE_IDS.specializations.phys.appuiFeu,
    major: ROLE_IDS.major.physique,
    color: COLORS.PHYS_BLUE,
    emoji: "🔷",
  }),
  spec_phys_demolition: specialization({
    key: "spec_phys_demolition",
    label: "Unité de Démolition",
    code: "SPEC // PHYS // DÉMOLITION",
    group: "spec_phys",
    branch: "phys",
    target: ROLE_IDS.specializations.phys.demolition,
    major: ROLE_IDS.major.physique,
    color: COLORS.PHYS_BLUE,
    emoji: "🔷",
  }),
  spec_phys_tpte: specialization({
    key: "spec_phys_tpte",
    label: "Unité TP/TE",
    code: "SPEC // PHYS // TP-TE",
    group: "spec_phys",
    branch: "phys",
    target: ROLE_IDS.specializations.phys.tpTe,
    major: ROLE_IDS.major.physique,
    color: COLORS.PHYS_BLUE,
    emoji: "🔷",
  }),

  spec_ptol_medical: specialization({
    key: "spec_ptol_medical",
    label: "Opérateur Médical",
    code: "SPEC // PTOL // MÉDICAL",
    group: "spec_ptol",
    branch: "ptol",
    target: ROLE_IDS.specializations.ptol.medical,
    major: ROLE_IDS.major.ptolemee,
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟩",
  }),
  spec_ptol_drone: specialization({
    key: "spec_ptol_drone",
    label: "Opérateur Drône",
    code: "SPEC // PTOL // DRÔNE",
    group: "spec_ptol",
    branch: "ptol",
    target: ROLE_IDS.specializations.ptol.drone,
    major: ROLE_IDS.major.ptolemee,
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟩",
  }),
  spec_ptol_motorise: specialization({
    key: "spec_ptol_motorise",
    label: "Opérateur Motorisé",
    code: "SPEC // PTOL // MOTORISÉ",
    group: "spec_ptol",
    branch: "ptol",
    target: ROLE_IDS.specializations.ptol.motorise,
    major: ROLE_IDS.major.ptolemee,
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟩",
  }),
  spec_ptol_genie: specialization({
    key: "spec_ptol_genie",
    label: "Opérateur du Génie",
    code: "SPEC // PTOL // GÉNIE",
    group: "spec_ptol",
    branch: "ptol",
    target: ROLE_IDS.specializations.ptol.genie,
    major: ROLE_IDS.major.ptolemee,
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟩",
  }),
  spec_ptol_quartier_maitre: specialization({
    key: "spec_ptol_quartier_maitre",
    label: "Quartier-Maître",
    code: "SPEC // PTOL // QUARTIER-MAÎTRE",
    group: "spec_ptol",
    branch: "ptol",
    target: ROLE_IDS.specializations.ptol.quartierMaitre,
    major: ROLE_IDS.major.ptolemee,
    color: COLORS.PTOLEMEE_GREEN,
    emoji: "🟩",
  }),
};

module.exports = { SPECIALIZATION_REQUESTS };
